# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03534e44aa4b91e6e2d1384a79016e1e8fd2cd124d7b3a82d5d8698a03d0e19a951d027b4f486a03002cb8af19da4ef17a64194b2132a789f3fc389b4e9c1ba9

test:
  secret_key_base: 697d25a3bd280d7135b2c97e0f676b3a4d073e10d181ca9b2c35c4c5d3c6b1ce4d20be51fa462a87542943c1cdf858c0b7ab204b93a4ab2d2237279fd9529447

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
